// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmiia_85KcjykpDahOHiKjM_82W5occI0',
    appId: '1:99084922684:web:f575de1a831e33e6a5b839',
    messagingSenderId: '99084922684',
    projectId: 'demoproject-e7c55',
    authDomain: 'demoproject-e7c55.firebaseapp.com',
    storageBucket: 'demoproject-e7c55.firebasestorage.app',
    measurementId: 'G-WTN91RR3HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzB8tpb3sPTlzosiIoLvru7y3By9b020',
    appId: '1:99084922684:android:0873019c470d218aa5b839',
    messagingSenderId: '99084922684',
    projectId: 'demoproject-e7c55',
    storageBucket: 'demoproject-e7c55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-iBWXnqKx_8IeP2pEChm7qbuLqB3nkZY',
    appId: '1:99084922684:ios:c1c64b3eb260be4da5b839',
    messagingSenderId: '99084922684',
    projectId: 'demoproject-e7c55',
    storageBucket: 'demoproject-e7c55.firebasestorage.app',
    iosBundleId: 'com.example.cse464P005Trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-iBWXnqKx_8IeP2pEChm7qbuLqB3nkZY',
    appId: '1:99084922684:ios:c1c64b3eb260be4da5b839',
    messagingSenderId: '99084922684',
    projectId: 'demoproject-e7c55',
    storageBucket: 'demoproject-e7c55.firebasestorage.app',
    iosBundleId: 'com.example.cse464P005Trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmiia_85KcjykpDahOHiKjM_82W5occI0',
    appId: '1:99084922684:web:1f875c164b06edf3a5b839',
    messagingSenderId: '99084922684',
    projectId: 'demoproject-e7c55',
    authDomain: 'demoproject-e7c55.firebaseapp.com',
    storageBucket: 'demoproject-e7c55.firebasestorage.app',
    measurementId: 'G-E1518JGZPG',
  );
}
